### ISSUE TITLE
Request context "method" value regression

### ISSUE THREAD

**Issue by movinfinex** [imposter-project/imposter-jvm-engine#679]
With this config:

```
---
plugin: rest
resources:
- path: "/method"
  method: get
  response:
    scriptFile: script.js
```

and this script file:
```
respond().withContent(JSON.stringify(context.request.method));
```

the response is `"GET"` until v4.2.4, but starting with v4.3.0 it's `{}`.
